LoginMVCFramework/Controllers/InicioController.cs
using AutoMapper;
using LoginMVCFramework.Models;
using RH.Login.Entidades.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoginMVCFramework.Filtros;
using System.Threading.Tasks;
using System.Web.Security;
using RH.Login.Negocios;
using System.IO;
using LoginMVCFramework.Controllers;

namespace LoginMVCFramework.Controllers
{

    public class InicioController : Controller
    {
        // GET: Inicio
        public ActionResult Login()
        {
            return View();
        }

        //Metodo que se ejecuta cuando el usuario da click desde su correo electronico para validar que tenga el token correctamente, donde se validan datos para recuperar su contraseña
        public ActionResult ValidarSolicitudCambioPassword(string token)
        {
            if (!string.IsNullOrWhiteSpace(token))
            {
                ServiciosAPINegocio service = new ServiciosAPINegocio();

                if (service.esTokenValido(token))
                {
                    if (service.GetTokenExpirationTime(token))
                    {

                        var datosDesencriptados = service.ObtenerTokenDesencriptado(token);

                        if (ResetPasswordNegocio.VerificaFolioEstaActivoSinExpirar(Convert.ToInt32( datosDesencriptados.FolioSolicitud ))) 
                        {
                            bool existeCuenta = ResetPasswordNegocio.ExisteUsuarioParaReset(datosDesencriptados.NumeroEmpleado, datosDesencriptados.NombreUsuario);

                            if (existeCuenta)
                            {
                                int idCuentaUsuarioCambiaPass = AutentificaciónNegocio.ObtenerIdRegistroEnAlphaDesdeUsuario(datosDesencriptados.NombreUsuario);
                                if (idCuentaUsuarioCambiaPass != 0)
                                {
                                    ViewBag.NombreCompleto = datosDesencriptados.NombreEmpleado;
                                    ViewBag.NombreUsuario = datosDesencriptados.NombreUsuario;
                                    ViewBag.folioSolicitud = datosDesencriptados.FolioSolicitud;
                                    ViewBag.idCuentaUsuarioCambiaPass = idCuentaUsuarioCambiaPass;

                                    return View();
                                }
                            }
                        }
                    }
                }

            }
           return RedirectToAction("ErrorEnVistaSolicitada", "Errores");
        }


        [HttpPost]
        public async Task<ActionResult> InicioDeSesion(AutenticacionModel Autenticacion  /* string User , string Password , string DireccionMac  ,  string HostNameCliente */ )
        {
            //int codigoResultado = 403; //403 - Prohibido 
            int codigoResultado = 401; //401-  No autorizado 
            string mensajeCliente = "";
            string JWT = "";
            if (ModelState.IsValid)
            {
                /*  status - Cadena  
                *      0  - La Autenticacion se cumplio con exito en todos los criterios
                *      1  - La autenticacion del usuario o contraseña es incorrecta 
                *      2  - La autenticacion de la mac y el host no se encuentan registrados 
                *      3 - El usuario no esta autorizado para usuar ALPHABET 
                */

              
                AutenticacionDTO autenticarDatos = Mapper.Map<AutenticacionDTO>(Autenticacion);
                int IdUsuarioEnAlpha = RH.Login.Negocios.AutentificaciónNegocio.ObtenerIdRegistroEnAlphaDesdeUsuario(autenticarDatos.User);
                int estatusAutenticacion = RH.Login.Negocios.AutentificaciónNegocio.AutenticarUsuario(autenticarDatos,   IdUsuarioEnAlpha);


                UsuarioInfDTO infoUsuarioRecuperada = new UsuarioInfDTO();
                switch (estatusAutenticacion)
                {
                    case 0:
                        string numEmpleado = RH.Login.Negocios.AutentificaciónNegocio.ObtenerNumEmpleadoDesdeUsuario(autenticarDatos.User);
                        infoUsuarioRecuperada = RH.Login.Negocios.AutentificaciónNegocio.ObtenerInfoUsuario(numEmpleado);

                        infoUsuarioRecuperada.IdUsuarioEnAlpha = IdUsuarioEnAlpha;
                        infoUsuarioRecuperada.IdUsuarioEnLoginCentralizado = RH.Login.Negocios.DBLoginCentralizadoNegocio.ObtenerIdUsuarioEnLoginCentralizado(infoUsuarioRecuperada.IdUsuarioEnAlpha);
                        infoUsuarioRecuperada.EsUsuarioRoot = false;
                        infoUsuarioRecuperada.Roles = DBLoginCentralizadoNegocio.ObtenerRolesUsuarioWeb(infoUsuarioRecuperada.IdUsuarioEnLoginCentralizado);
                        infoUsuarioRecuperada.JWT = infoUsuarioRecuperada.Roles != null ? await RH.Login.Negocios.ServiciosAPINegocio.ObtenerToken(numEmpleado, Autenticacion.User, infoUsuarioRecuperada.Roles) : null;
                        Session["User"] = infoUsuarioRecuperada;
                        codigoResultado = 200;
                        mensajeCliente = "La Autenticacion se cumplio con exito";
                        break;
                    case 1:
                        mensajeCliente = "El Usuario y/o la contraseña es incorrecta";
                        break;
                    case 2:
                        mensajeCliente = "Este equipo no se encuentra autorizado para usar los aplicativos webs";
                        break;
                    case 3:
                        mensajeCliente = "El usuario no esta autorizado para usar ALPHABET , Contacte con un administrador del sistema";
                        break;
                }

                if (infoUsuarioRecuperada.JWT != null)
                {
                    FormsAuthentication.SetAuthCookie(infoUsuarioRecuperada.JWT, false);

                    return Json(new
                    {
                        RespuestaServidor = new HttpStatusCodeResult(codigoResultado, mensajeCliente)

                    });

                }
                else
                {
                    return Json(new
                    {
                        RespuestaServidor = new HttpStatusCodeResult(401, mensajeCliente == "" ? "Ocurrio un error firmando la autorizacion contacte con el desarrollador" : mensajeCliente)
                    });
                }


            }
            else
            {
                return Json(new
                {
                    RespuestaServidor = new HttpStatusCodeResult(codigoResultado, mensajeCliente)
                });
            }

        }


        public FilePathResult DescargarValidadorCliente()
        {
            string path = Path.Combine(Server.MapPath("~/"), "Dowloads/WizardLogin.rar");

            return File(path, "application/octet-stream", "Validador_v" + DateTime.Now.Month + ".0.0.rar");
        }





        //Metodo que se incovo al solicitar la recuperacion de la contraseña via web 
        public async Task<ActionResult> SolicitarCambioPassword(LoginMVCFramework.Models.ModelosDatosEntrada.SolicitudCambioPassword.SolicitarCambioPasswordModel nuevaSolicitud )
        {
           
            string mensajeObtenido = "El equipo desde donde se intenta solicitar el cambio de contraseña no esta autorizado para esta acción";
            int codigoResultadoServer = 403;
            if (ModelState.IsValid)
            {
                RH.Login.Entidades.DTO.InicioDTO.SolicitudCambioPasswordDTO nuevasolicitudDTO = Mapper.Map<RH.Login.Entidades.DTO.InicioDTO.SolicitudCambioPasswordDTO>(nuevaSolicitud);
                bool esPcAutorizada = AutentificaciónNegocio.EsComputadoraAutorizada(nuevasolicitudDTO.direccionMac, nuevasolicitudDTO.hostNameCliente);

                if (esPcAutorizada)
                {

                    mensajeObtenido = await ResetPasswordNegocio.solicitarCambioContraseniaCorreoElectronico(  nuevasolicitudDTO );

                    if (mensajeObtenido.Contains("TIMEERROR"))
                    {
                        //var e = mensajeObtenido.Split('|').Where(x => x != "");
                        mensajeObtenido = mensajeObtenido.Split('|').Where(x => x != "").Skip(1).FirstOrDefault().Trim();
                        /*No autoritazado para hacer otra solicitud*/
                        codigoResultadoServer = 401;
                    }
                    else 
                    {
                        codigoResultadoServer = mensajeObtenido.ToString().Contains("ERROR ") ? 403 : 200;
                    }

                }
            }
             

            return Json(new
            {
                RespuestaServidor = new HttpStatusCodeResult(codigoResultadoServer, mensajeObtenido.ToString())
            });

        }


        public ActionResult SolicitudConfirmadaCambiaPassword(LoginMVCFramework.Models.ModelosDatosEntrada.SolicitudCambioPassword.SolicitudAprobadaCambioPasswordModel solicitudAprobada ) 
        {
            string mensajeObtenido = "El equipo desde donde se intenta solicitar el cambio de contraseña no esta autorizado para esta acción";
            int codigoResultadoServer = 403;
            bool esCorrectoCambioPass = false;
            if (ModelState.IsValid) 
            {

                bool esPcAutorizada = AutentificaciónNegocio.EsComputadoraAutorizada(solicitudAprobada.direccionMac , solicitudAprobada.hostNameCliente);

                if (esPcAutorizada)
                {
                    if (ResetPasswordNegocio.VerificaFolioEstaActivoSinExpirar(solicitudAprobada.folioSolicitud))
                    {
                        esCorrectoCambioPass = ResetPasswordNegocio.cambiarPassworsSolicitudAprobada(solicitudAprobada.idCuentaUsuarioCambiaPass, solicitudAprobada.sustituirPassword, solicitudAprobada.nombreUsuario);
                        codigoResultadoServer = esCorrectoCambioPass ? 200 : 403;

LoginMVCFramework/Controllers/SesionUsuarioController.cs
using AutoMapper;
using LoginMVCFramework.Filtros;
using LoginMVCFramework.Models;
using RH.Login.Entidades.DTO;
using RH.Login.Negocios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace LoginMVCFramework.Controllers
{
    [FiltroSeguridadSesion]
    public class SesionUsuarioController : Controller
    {

        public ActionResult InicioApp()
        {
            LoginMVCFramework.Models.InformacionUsuarioModel informacionUsuario = Mapper.Map<InformacionUsuarioModel>((UsuarioInfDTO)Session["User"]);
            informacionUsuario.EsUsuarioRoot = RH.Login.Negocios.DBLoginCentralizadoNegocio.VerificarSiElUsuarioEsRoot(informacionUsuario.IdUsuarioEnAlpha);
            informacionUsuario.EsUsuarioNuevo = AutentificaciónNegocio.EsUsuarioNuevo(informacionUsuario.IdUsuarioEnAlpha);

            ViewBag.idCuentaUsuarioCambiaPass = informacionUsuario.EsUsuarioNuevo == true ? informacionUsuario.IdUsuarioEnAlpha : 0;

            ViewBag.Aplicaciones = DBLoginCentralizadoNegocio.ObtenerAplicacionesAsignadas(informacionUsuario.IdUsuarioEnLoginCentralizado);

            return View(informacionUsuario);
        }


        [HttpGet]
        //[HttpPost]
        public HttpResponseBase CrearUrl(int idCatAppServidor, int idTblUsuario) 
        {
            LoginMVCFramework.Models.InformacionUsuarioModel informacionUsuario = Mapper.Map<InformacionUsuarioModel>((UsuarioInfDTO)Session["User"]);
            bool estaAutorizado = DBLoginCentralizadoNegocio.ValidarAccesoAppUsuario( idTblUsuario, idCatAppServidor);


            string rutaRedireccionar = "";
            string direccionservervidor = "";
            if (!estaAutorizado)
            {
                direccionservervidor = System.Diagnostics.Debugger.IsAttached ? "localhost:44312" : "172.19.3.171:85";/* ruta que tendra dentro del servidor*/
                rutaRedireccionar = $"http://{direccionservervidor}/Errores/ErrorEnVistaSolicitada";
            }
            else 
            {
                //local hace referencia al aplicativo de foliacion con el cual se estan realizando pruebas y cuando se obtiene la url es de rutas de los servidores de pruebas
                direccionservervidor = System.Diagnostics.Debugger.IsAttached ? "localhost:52797" : DBLoginCentralizadoNegocio.ObtenerUrlApp(idTblUsuario, idCatAppServidor);
                rutaRedireccionar = $"http://{direccionservervidor}/Validador/ValidaToken?token={informacionUsuario.JWT.Trim()}";
            }



            //Correcto
            if (HttpContext.Response.IsClientConnected)
            {
                HttpContext.Response.StatusCode = 200;
                //HttpContext.Response.AppendHeader("Toooooken", informacionUsuario.JWT);
                HttpContext.Response.AppendHeader("Access-Control-Allow-Origin", "*");
                HttpContext.Response.Redirect(rutaRedireccionar, true);
                HttpContext.Response.End();
            }


            return HttpContext.Response;
        }


        [HttpPost]
        public ActionResult CambiarPasswordUsuarioNuevo(string nuevaContrasenia , int idCuentaUsuarioCambiaPass)
        {
            bool esCorrectoCambioPass = false;
            int codigoResultado = 403;

            if (!string.IsNullOrEmpty(nuevaContrasenia) || idCuentaUsuarioCambiaPass != 0) 
            {
                esCorrectoCambioPass = ResetPasswordNegocio.cambiarPassworsUsuarioNuevo(idCuentaUsuarioCambiaPass, nuevaContrasenia);

                 codigoResultado = esCorrectoCambioPass ? 200 : 403;
                
            }

            string mensaje = esCorrectoCambioPass ? "Se cambio su contraseña correctamente" : "Ocurrio un error al intentar cambiar su contraseña";

            return Json(new
            {
                RespuestaServidor = new HttpStatusCodeResult(codigoResultado, mensaje)

            });

        }



        public ActionResult CerrarSesion()
        {
            FormsAuthentication.SignOut();
            Session["User"] = null;

            return RedirectToAction("Login", "Inicio");
        }

    }
}

LoginMVCFramework/Views/Inicio/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Login.cshtml";
}


<section  >

    <div class="vh-100 Text_Color" >
        <div class="container-fluid h-custom">

            <div class="row d-flex justify-content-center align-items-center h-100">

                <div class="col-md-9 col-lg-6 col-xl-5" style="padding-bottom: 40px;">
                    <img src="~/Content/Imagenes/LOGO GOBIERNO DE CAMPECHE_2021_2027.png" class="img-fluid" alt="Sample image" style="height: 600px; width:650px; margin-top:6px;">
                </div>
                <br />


                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1" style="background-color:#FFFFFF; border-radius:16px; ">

                    <div class="divider d-flex align-items-center my-4">

                    </div>

                    <div class="text-center">
                        <p class="lead fw-normal mb-0 me-3 fw-bold">INICIO EN ALPHABET</p>

                    </div>
                    <br />
                    <!-- User input -->
                    <div class="form-floating">
                        <input id="User" class="form-control" placeholder="Usuario" />
                        <label for="floatingInput">Usuario:</label>

                    </div>
                    <br />
                    <!-- Password input -->
                    @*<div class="form-floating">
                        <input id="Password" type="password" class="form-control" placeholder="Contraseña" />
                        <label for="floatingPassword">Contraseña:</label>

                    </div>*@

                    <!--- -->
                    <!--- -->

                    <div class="form-floating">
                        <input id="Password" type="password" class="form-control passwordInicial" placeholder="nueva contraseña" />
                        <label for="floatingInput">Contraseña:</label>
                        <!--- <span class="fa fa-fw fa-eye password-icon show-password2"></span> -->
                    </div>
             
                    <div style="text-align:right; margin-top:8px;">
                        <input type="checkbox" onclick="MostrarPasswordIniarSession()" /> <label for="MostrarPass">Mostrar contraseña</label>
                    </div>
                    <!--- -->
                    <!--- -->


                    <br />
                    <div class="col-12 text-center">
                        
                        <button id="BotonPrimario" class="btn btn-lg  marginBotton" onclick="Iniciar()"
                                style="padding-left: 2.5rem; padding-right: 2.5rem;">
                            Iniciar
                        </button>
                        <small>
                           
                            <p class="small fw-bold mt-2 pt-1 mb-0">¿HAZ OLVIDADO TU CONTRASEÑA?  <a class="link-danger pointer" onclick="AbrirModalSolicitarContraseña()"> Recuperar</a></p>
                            <p class="small fw-bold mt-2 pt-1 mb-0">¿TE INTERESA ALPHA WEB? <a class="link-primary" href="@Url.Action("DescargarValidadorCliente", "Inicio")">  Validador <i class="fas fa-cloud-download-alt"></i> </a></p>

                        </small>
                        
                    </div>
                    <div class="divider d-flex align-items-center my-4">

                    </div>


                </div>
            </div>
        </div>

    </div>

</section>












<!-- Modal -->
<div class="modal fade" id="RecuperarContrasenia" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <section>
                    <div class=" text-center">
                        <img class="margen" src="~/Content/Imagenes/ESCUDO_GRIS.png" alt="Sample image" style="height: 200px; width:120px; margin-top:6px;">

                        <h2 class="margen">CAMBIAR CONTRASEÑA</h2>

                        <div class="form-floating margen">
                            <input id="usuarioRecuperarPass" class="form-control" placeholder="USUARIO" />
                            <label for="floatingInput">Usuario: </label>
                        </div>


                        <div class="form-floating margen">
                            <input id="numeroEmpleadoRecuperarPass" type="number" class="form-control" placeholder="NUMERO EMPLEADO" />
                            <label for="floatingInput">Numero Empleado:</label>

                        </div>


                        <div id="DivTiempoEspera" class="col-12 margen text-center" style=" background-color: rgb(236, 235, 235); display: none;">
                            <small id="SegundosEspera" style="color: grey; font-size: 18px; font-weight: bold;"> ...</small>
                        </div>

                        <div class="col-12 text-center margen">
                            <button id="BotonPrimarioSolicitarCambioPass" class="btn btn-lg " onclick="SolicitarCambioPasswordDesdeWeb()" >
                                Recuperar
                            </button>
                        </div>

                    </div>
                </section>


            </div>

        </div>
    </div>
</div>

LoginMVCFramework/Views/Inicio/ValidarSolicitudCambioPassword.cshtml
@{
    Layout = "~/Views/Shared/_Login.cshtml";
}


<section class="col-12 offset-sm-1 col-sm-10" style="background-color: white ; border-radius: 16px; margin-top: 50px; ">

    <br>
    <div class="col-12 offset-sm-1 col-sm-4  marginBotton marginTop">
        <a href="@Url.Action("InicioApp", "SesionUsuario")"> <button id="BotonPrimario" class="col-md-4 col-12 btn BotonConAccion" title="Regresar a la pagina de inicio"> <i class="fas fa-arrow-left"> Inicio </i>  </button></a>
    </div>
    
    <br>
    <div class="offset-1 col-10 offset-sm-2 col-sm-8 text-center" style="background-color: rgba(243, 247, 15, 0.61); border-radius: 24px;">
        <br>
        <h4>Hemos detectado la solicitud de recuperacion : </h4>
        <h4>De su cuenta al "ECOSISTEMA ALPHABET" </h4>
        <div class="row">
            <h5>Para mantener la seguridad de su cuenta le sugerimos "NO COMPARTIR":</h5>
            <ol>
                <ul>Contraseñas.</ul>
                <ul>Nombres de usuario.</ul>
                <ul>Correos Electronicos.</ul>
            </ol>
        </div>

        <h6 style="color: red;">Si usted no solicito el cambio de su contraseña comunícaselo a un desarrollador.</h6>
        <br>
    </div>

    <br>
    <div class="col-12 offset-sm-3 col-sm-6 text-center">

        <hr>

        @*<h2>Hola, Bienvendido Edgar Manzanilla</h2>
        <P>Esta a un paso de recuperar el acceso al "ECOSISTEMA APLHA"</P>

        <hr>*@
        <span style="font-size: 32px; font-weight:bold; "> Hola, Bienvendido </span>

        <br />
        <span class="margen" style="font-size: 24px; font-weight:bold; ">@ViewBag.NombreCompleto </span>
        <br />
        <br />
        <br />
        <P class="margen" style="font-size:16px; font-weight:bold; letter-spacing:normal;">Esta a un paso de recuperar el acceso al "ECOSISTEMA APLHABET" desde su cuenta <span id="nombreUsuarioSolicitud" style="font-size:24px;"> "@ViewBag.NombreUsuario"</span></P>
        <br />





        <h3 class="margen">CAMBIE SU CONTRASEÑA</h3>


        @*<div class="form-floating margen">
            <input id="cambioPassword" type="password" class="form-control" placeholder="nueva contraseña" />
            <label for="floatingInput">Nueva contraseña:</label>

        </div>
        <br>

        <div class="form-floating margen">
            <input id="repiteCambioPassword" type="password" class="form-control" placeholder="Repita su nueva contraseña" />
            <label for="floatingInput">Repita su nueva contraseña: </label>
        </div>*@


        <div class="form-floating margen">
            <input id="cambioPassword" type="password" name="password" class="form-control password1" placeholder="nueva contraseña" />
            <label for="floatingInput">Nueva contraseña:</label>
            <!--- <span class="fa fa-fw fa-eye password-icon show-password2"></span> -->
        </div>

        <div class="form-floating ">
            <input id="repiteCambioPassword" type="password" name="password2" class="form-control password2" placeholder="Repita su nueva contraseña" />
            <label for="floatingInput">Repita su nueva contraseña: </label>
        </div>

        <br />

        <div style="text-align:right;">
            <input  type="checkbox" onclick="MostrarPassword()" /> <label for="MostrarPass">Mostrar contraseñas</label>
        </div>

        <ol class="margen" style="text-align: left;">
            <small class="form-text text-muted">
                Las claves deben:
            <li>Coincidir</li>
            <li>No tener espacios en blanco</li>
            <li>No estar vacias</li>

            </small>
        </ol>


        <div class="col-12 text-center margen">
            <button id="BotonPrimario" class="btn btn-lg" onclick="CambiarPasswordSolicitudExitosa(@ViewBag.idCuentaUsuarioCambiaPass , @ViewBag.folioSolicitud )">
                Cambiar contraseña
            </button>
        </div>
        <br>
    </div>




</section>